// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaOnline.AppMVC.Models;

#nullable disable

namespace TiendaOnline.AppMVC.Migrations
{
    [DbContext(typeof(TiendaOnlineZapContext))]
    partial class TiendaOnlineZapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.AjustesInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__AjustesI__3214EC0759E41A65");

                    b.HasIndex("InventarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AjustesInventarios");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("ACTIVO");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Carritos__3214EC07FFE668A5");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC0798379AD1");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Categori__75E3EFCF351C20E8")
                        .IsUnique();

                    b.ToTable("Categorias", t =>
                        {
                            t.HasCheckConstraint("CHK_Categorias_Estatus", "[Estatus] IN (0,1)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Colore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoHex")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Colores__3214EC07C78C3D1E");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Colores__75E3EFCF86E3D4E6")
                        .IsUnique();

                    b.ToTable("Colores", t =>
                        {
                            t.HasCheckConstraint("CHK_Colores_Estatus", "[Estatus] IN (0,1)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Cupone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<decimal>("MontoMinimoCompra")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TipoDescuento")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("UsoMaximo")
                        .HasColumnType("int");

                    b.Property<int?>("UsoPorUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorDescuento")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Cupones__3214EC07D85B54F7");

                    b.HasIndex(new[] { "Codigo" }, "UQ__Cupones__06370DAC3FE68CC8")
                        .IsUnique();

                    b.ToTable("Cupones", t =>
                        {
                            t.HasCheckConstraint("CHK_Cupones_Estatus", "[Estatus] IN (0,1)");

                            t.HasCheckConstraint("CHK_Cupones_Fechas", "[FechaFin] >= [FechaInicio]");

                            t.HasCheckConstraint("CHK_Cupones_TipoDescuento", "[TipoDescuento] IN ('PORCENTAJE', 'MONTO')");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.DetallesCarrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CarritoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Detalles__3214EC07AA22E78E");

                    b.HasIndex("InventarioId");

                    b.HasIndex(new[] { "CarritoId", "InventarioId" }, "UQ_DetallesCarritos_CarritoId_InventarioId")
                        .IsUnique();

                    b.ToTable("DetallesCarritos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.DetallesPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("InventarioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TallaTexto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Detalles__3214EC079ADE60F7");

                    b.HasIndex("InventarioId");

                    b.HasIndex("PedidoId");

                    b.ToTable("DetallesPedidos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.DireccionesUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Direccio__3214EC074A853243");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DireccionesUsuarios", t =>
                        {
                            t.HasCheckConstraint("CHK_DireccionesUsuarios_Estatus", "[Estatus] IN (0,1)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.EstadosPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__EstadosP__3214EC078BEC3F4E");

                    b.HasIndex(new[] { "Nombre" }, "UQ__EstadosP__75E3EFCFE6716995")
                        .IsUnique();

                    b.ToTable("EstadosPedidos", t =>
                        {
                            t.HasCheckConstraint("CHK_EstadosPedidos_Estatus", "[Estatus] IN (0,1)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.HistorialesEstadosPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("EstadoPedidoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Historia__3214EC07C105584E");

                    b.HasIndex("EstadoPedidoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialesEstadosPedidos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<int>("TallaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Inventar__3214EC07F2B9711F");

                    b.HasIndex("TallaId");

                    b.HasIndex(new[] { "ProductoId", "TallaId" }, "UQ_Inventarios_ProductoId_TallaId")
                        .IsUnique();

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id")
                        .HasName("PK__Marcas__3214EC07DB268714");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Marcas__75E3EFCFD2041FB1")
                        .IsUnique();

                    b.ToTable("Marcas", t =>
                        {
                            t.HasCheckConstraint("CHK_Marcas_Estatus", "[Estatus] IN (0,1)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.MetodosEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TiempoEstimado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__MetodosE__3214EC070FEED193");

                    b.HasIndex(new[] { "Nombre" }, "UQ__MetodosE__75E3EFCF411DBC99")
                        .IsUnique();

                    b.ToTable("MetodosEnvio", null, t =>
                        {
                            t.HasCheckConstraint("CHK_MetodosEnvio_Estatus", "[Estatus] IN (0,1)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.MetodosPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__MetodosP__3214EC079FCA3954");

                    b.HasIndex(new[] { "Nombre" }, "UQ__MetodosP__75E3EFCFDE4488B0")
                        .IsUnique();

                    b.ToTable("MetodosPago", null, t =>
                        {
                            t.HasCheckConstraint("CHK_MetodosPago_Estatus", "[Estatus] IN (0,1)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Notificacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsLeida")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Notifica__3214EC075D4FBDF8");

                    b.HasIndex("PedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<string>("ReferenciaTransaccion")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("RespuestaPasarela")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Pagos__3214EC07FF352D86");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoCliente")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("CuponId")
                        .HasColumnType("int");

                    b.Property<decimal>("DescuentoTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("DireccionEntrega")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("DireccionUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("EstadoPedidoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MetodoEnvioId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ReferenciaEntrega")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TelefonoCliente")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Pedido__09BA1430D944A24F");

                    b.HasIndex("CuponId");

                    b.HasIndex("DireccionUsuarioId");

                    b.HasIndex("EstadoPedidoId");

                    b.HasIndex("MetodoEnvioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("EsDestacado")
                        .HasColumnType("bit");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Producto__A430AEA3C8F52465");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.HasIndex(new[] { "Sku" }, "UQ_Productos_Sku")
                        .IsUnique();

                    b.HasIndex(new[] { "Nombre" }, "UQ__Producto__75E3EFCFF3D3F582")
                        .IsUnique();

                    b.ToTable("Productos", t =>
                        {
                            t.HasCheckConstraint("CHK_Productos_Estatus", "[Estatus] IN (0,1)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.ProductosColore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Producto__3214EC075A7A8784");

                    b.HasIndex("ColorId");

                    b.HasIndex(new[] { "ProductoId", "ColorId" }, "UQ_ProductosColores_ProductoId_ColorId")
                        .IsUnique();

                    b.ToTable("ProductosColores");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.ProductosImagene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id")
                        .HasName("PK__Producto__2DA9E6096F42F20A");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductosImagenes");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC0713DBC2AF");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Roles__75E3EFCF1BF7A26A")
                        .IsUnique();

                    b.ToTable("Roles", t =>
                        {
                            t.HasCheckConstraint("CHK_Roles_Estatus", "[Estatus] IN (0,1)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Talla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Tallas__3214EC0710782118");

                    b.HasIndex(new[] { "Numero" }, "UQ__Tallas__7E532BC6A265B055")
                        .IsUnique();

                    b.ToTable("Tallas", t =>
                        {
                            t.HasCheckConstraint("CHK_Tallas_Estatus", "[Estatus] IN (0,1)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.UsosCupone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaUso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("MontoDescuentoAplicado")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UsosCupo__3214EC07BC8598BE");

                    b.HasIndex("CuponId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex(new[] { "PedidoId" }, "UQ_UsosCupones_PedidoId")
                        .IsUnique();

                    b.ToTable("UsosCupones");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<byte>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Usuario__2B3DE7B8550B75B7");

                    b.HasIndex("RolId");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuario__60695A19B064666A")
                        .IsUnique();

                    b.ToTable("Usuarios", t =>
                        {
                            t.HasCheckConstraint("CHK_Usuarios_Estatus", "[Estatus] IN (1,2,3,4)");
                        });
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.AjustesInventario", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Inventario", "Inventario")
                        .WithMany("AjustesInventarios")
                        .HasForeignKey("InventarioId")
                        .IsRequired()
                        .HasConstraintName("FK_AjustesInventarios_Inventarios");

                    b.HasOne("TiendaOnline.AppMVC.Models.Usuario", "Usuario")
                        .WithMany("AjustesInventarios")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_AjustesInventarios_Usuarios");

                    b.Navigation("Inventario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Carrito", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Usuario", "Usuario")
                        .WithMany("Carritos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Carritos_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.DetallesCarrito", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Carrito", "Carrito")
                        .WithMany("DetallesCarritos")
                        .HasForeignKey("CarritoId")
                        .IsRequired()
                        .HasConstraintName("FK_DetallesCarritos_Carritos");

                    b.HasOne("TiendaOnline.AppMVC.Models.Inventario", "Inventario")
                        .WithMany("DetallesCarritos")
                        .HasForeignKey("InventarioId")
                        .IsRequired()
                        .HasConstraintName("FK_DetallesCarritos_Inventarios");

                    b.Navigation("Carrito");

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.DetallesPedido", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Inventario", "Inventario")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("InventarioId")
                        .IsRequired()
                        .HasConstraintName("FK_DetallesPedidos_Inventarios");

                    b.HasOne("TiendaOnline.AppMVC.Models.Pedido", "Pedido")
                        .WithMany("DetallesPedidos")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("FK_DetallesPedidos_Pedidos");

                    b.Navigation("Inventario");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.DireccionesUsuario", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Usuario", "Usuario")
                        .WithMany("DireccionesUsuarios")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_DireccionesUsuarios_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.HistorialesEstadosPedido", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.EstadosPedido", "EstadoPedido")
                        .WithMany("HistorialesEstadosPedidos")
                        .HasForeignKey("EstadoPedidoId")
                        .IsRequired()
                        .HasConstraintName("FK_HistorialesEstadosPedidos_EstadosPedidos");

                    b.HasOne("TiendaOnline.AppMVC.Models.Pedido", "Pedido")
                        .WithMany("HistorialesEstadosPedidos")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("FK_HistorialesEstadosPedidos_Pedidos");

                    b.HasOne("TiendaOnline.AppMVC.Models.Usuario", "Usuario")
                        .WithMany("HistorialesEstadosPedidos")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK_HistorialesEstadosPedidos_Usuarios");

                    b.Navigation("EstadoPedido");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Inventario", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_Inventarios_Productos");

                    b.HasOne("TiendaOnline.AppMVC.Models.Talla", "Talla")
                        .WithMany("Inventarios")
                        .HasForeignKey("TallaId")
                        .IsRequired()
                        .HasConstraintName("FK_Inventarios_Tallas");

                    b.Navigation("Producto");

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Notificacione", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Pedido", "Pedido")
                        .WithMany("Notificaciones")
                        .HasForeignKey("PedidoId")
                        .HasConstraintName("FK_Notificaciones_Pedidos");

                    b.HasOne("TiendaOnline.AppMVC.Models.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Notificaciones_Usuarios");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Pago", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.MetodosPago", "MetodoPago")
                        .WithMany("Pagos")
                        .HasForeignKey("MetodoPagoId")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_MetodosPago");

                    b.HasOne("TiendaOnline.AppMVC.Models.Pedido", "Pedido")
                        .WithMany("Pagos")
                        .HasForeignKey("PedidoId")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_Pedidos");

                    b.Navigation("MetodoPago");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Pedido", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Cupone", "Cupon")
                        .WithMany("Pedidos")
                        .HasForeignKey("CuponId")
                        .HasConstraintName("FK_Pedidos_Cupones");

                    b.HasOne("TiendaOnline.AppMVC.Models.DireccionesUsuario", "DireccionUsuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("DireccionUsuarioId")
                        .HasConstraintName("FK_Pedidos_DireccionesUsuarios");

                    b.HasOne("TiendaOnline.AppMVC.Models.EstadosPedido", "EstadoPedido")
                        .WithMany("Pedidos")
                        .HasForeignKey("EstadoPedidoId")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_EstadosPedidos");

                    b.HasOne("TiendaOnline.AppMVC.Models.MetodosEnvio", "MetodoEnvio")
                        .WithMany("Pedidos")
                        .HasForeignKey("MetodoEnvioId")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_MetodosEnvio");

                    b.HasOne("TiendaOnline.AppMVC.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Pedidos_Usuarios");

                    b.Navigation("Cupon");

                    b.Navigation("DireccionUsuario");

                    b.Navigation("EstadoPedido");

                    b.Navigation("MetodoEnvio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Producto", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Categorias");

                    b.HasOne("TiendaOnline.AppMVC.Models.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Marcas");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.ProductosColore", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Colore", "Color")
                        .WithMany("ProductosColores")
                        .HasForeignKey("ColorId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductosColores_Colores");

                    b.HasOne("TiendaOnline.AppMVC.Models.Producto", "Producto")
                        .WithMany("ProductosColores")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductosColores_Productos");

                    b.Navigation("Color");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.ProductosImagene", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Producto", "Producto")
                        .WithMany("ProductosImagenes")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductosImagenes_Productos");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.UsosCupone", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Cupone", "Cupon")
                        .WithMany("UsosCupones")
                        .HasForeignKey("CuponId")
                        .IsRequired()
                        .HasConstraintName("FK_UsosCupones_Cupones");

                    b.HasOne("TiendaOnline.AppMVC.Models.Pedido", "Pedido")
                        .WithOne("UsosCupone")
                        .HasForeignKey("TiendaOnline.AppMVC.Models.UsosCupone", "PedidoId")
                        .IsRequired()
                        .HasConstraintName("FK_UsosCupones_Pedidos");

                    b.HasOne("TiendaOnline.AppMVC.Models.Usuario", "Usuario")
                        .WithMany("UsosCupones")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_UsosCupones_Usuarios");

                    b.Navigation("Cupon");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Usuario", b =>
                {
                    b.HasOne("TiendaOnline.AppMVC.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Carrito", b =>
                {
                    b.Navigation("DetallesCarritos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Colore", b =>
                {
                    b.Navigation("ProductosColores");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Cupone", b =>
                {
                    b.Navigation("Pedidos");

                    b.Navigation("UsosCupones");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.DireccionesUsuario", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.EstadosPedido", b =>
                {
                    b.Navigation("HistorialesEstadosPedidos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Inventario", b =>
                {
                    b.Navigation("AjustesInventarios");

                    b.Navigation("DetallesCarritos");

                    b.Navigation("DetallesPedidos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.MetodosEnvio", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.MetodosPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Pedido", b =>
                {
                    b.Navigation("DetallesPedidos");

                    b.Navigation("HistorialesEstadosPedidos");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pagos");

                    b.Navigation("UsosCupone");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Producto", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("ProductosColores");

                    b.Navigation("ProductosImagenes");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Talla", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("TiendaOnline.AppMVC.Models.Usuario", b =>
                {
                    b.Navigation("AjustesInventarios");

                    b.Navigation("Carritos");

                    b.Navigation("DireccionesUsuarios");

                    b.Navigation("HistorialesEstadosPedidos");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pedidos");

                    b.Navigation("UsosCupones");
                });
#pragma warning restore 612, 618
        }
    }
}
